### ISSUE TITLE
The picture seems dead

### ISSUE THREAD

**Issue by ice1000** [abccsss/LatoMath#1]

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/198150809-38851bb1-74cf-40ec-ad24-17e4f3fe3042.png)

**Comment by abccsss** [comment]
放一张图片在这，以获得永久链接。

![图片](https://user-images.githubusercontent.com/23280392/199365551-d8fb3a9e-e804-4ccf-9070-2c25e04dd1e8.png)
