### ISSUE TITLE
License and status

### ISSUE THREAD

**Issue by Enivex** [abccsss/LatoMath#3]
This is one of extremely few sans serif open-type math fonts, but cannot really be used for anything right now because of the missing software license. Could you please add a software license to this repository?

ps: This font was mentioned in the talk "An updated survey of opentype math fonts" at https://tug.org/tug2023/program.html

**Comment by abccsss** [comment]
Added a license [here](https://github.com/abccsss/LatoMath/commit/8c51e58f6460767f8b32e499d2c2dacb51a3f575).

I'm glad to hear that people have found this project helpful!
