### ISSUE TITLE
Suggestions for enhancement

### ISSUE THREAD

**Issue by dflipo** [abccsss/LatoMath#4]
I agree with other contributors who mentioned this sans-serif Math font as really useful, it is fairly complete and very pleasant to read.

I have noticed a few misses however:
-- mathslash (U+002F), backslash (U+005C), and double brackets (U+27E6, U+27E7) aren't extensible;
-- wide over accents missing: wideoverbar (U+0305), widebreve  (U+0306), widecheck (U+030C);
-- extensible over arrows missing:  U+20D0, U+20D1,  U+20D6, U+20D7, U+20E1;
-- wide under accents missing: wideutilde  (U+0330), wideoverbar (U+0332);
-- extensible under arrows missing:  U+034D, U+20EC,  U+20ED, U+20EE, U+20EF;

Please let me know how I can help for these enhancements, I would be happy to contribute to your project.

mathscr/mathcal and mathfrak alphabets are missing too, but they can be easily borrowed from other fonts, so that is less important for me.

**Comment by abccsss** [comment]
Done in v0.36 thanks to your efforts!
